vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /img/avatar
            upload_destination: '%kernel.project_dir%/public/img/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # delete-on-remove: false

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

