vich_uploader:
    db_driver: orm

    mappings:
        visuals:
            uri_prefix: /img/articles
            upload_destination: '%kernel.project_dir%/public/img/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove:   true
            inject_on_load:     true
            delete_on_update:   true

    metadata:
            type: attribute